
import { SprayBrand, SprayLine, SprayColor } from './types';

export const BRAND_COLORS: SprayColor[] = [
  // --- MOLOTOW PREMIUM 253 MASTER LIST (Categorized by Chart Rows) ---
  
  // Row 1: Yellows (001-015)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Jasmin Yellow", code: "001", hex: "#FDF551" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Zinc Yellow", code: "002", hex: "#F9E400" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cadmium Yellow", code: "003", hex: "#FFD700" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Signal Yellow", code: "004", hex: "#F5A300" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Nature White", code: "005", hex: "#F5F5F0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Vanilla", code: "006", hex: "#F3E5AB" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cashmere Yellow", code: "007", hex: "#EAD6A8" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Quince", code: "008", hex: "#FBC600" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Golden Yellow", code: "009", hex: "#F9AB00" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Melon Yellow", code: "010", hex: "#F68E00" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Slider Light Orange", code: "011", hex: "#FF9F52" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Pastel Orange", code: "012", hex: "#FFB380" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Dare Orange Light", code: "013", hex: "#FF7533" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Dare Orange", code: "014", hex: "#E94E1B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Linda's Sunset", code: "015", hex: "#F05A28" },

  // Row 2: Reds & Oranges (016-031)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Traffic Red", code: "016", hex: "#C00D0D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Tornado Red", code: "017", hex: "#D81E1E" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ruby Red", code: "018", hex: "#9B111E" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Burgundy", code: "019", hex: "#6B0F1A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Garnet", code: "020", hex: "#4D0A0A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Geser Black Red", code: "021", hex: "#3B0A0A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Loomit's Aubergine", code: "022", hex: "#483248" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Peach Pastel", code: "023", hex: "#FFDAB9" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Peach Light", code: "024", hex: "#FFCBA4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Peach", code: "025", hex: "#FFB07C" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Goldfish", code: "026", hex: "#FF9966" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lobster Light", code: "027", hex: "#F88379" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lobster Middle", code: "028", hex: "#ED6A5A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lobster", code: "029", hex: "#D0312D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Vermillion", code: "030", hex: "#E34234" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Shock Orange", code: "031", hex: "#FF4500" },

  // Row 3: Pinks & Magentas (032-062)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mad C Cherry Red", code: "032", hex: "#E20613" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Signal Red", code: "033", hex: "#C3002F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Apricot", code: "034", hex: "#F7A186" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Salmon Orange", code: "035", hex: "#F08080" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Autumn Leaf", code: "036", hex: "#B5651D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Loomit's Apricot Pastel", code: "037", hex: "#FFE5B4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Loomit's Apricot Light", code: "038", hex: "#FFD8B1" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Loomit's Apricot Middle", code: "039", hex: "#FFB347" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Loomit's Apricot", code: "040", hex: "#FB9902" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Strawberry Red", code: "041", hex: "#E34234" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Pussy Pink", code: "042", hex: "#FFC0CB" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Raspberry Red", code: "043", hex: "#E30B5D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sangria", code: "044", hex: "#922B3E" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grapefruit Light", code: "045", hex: "#FFC1CC" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grapefruit", code: "046", hex: "#F08080" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mauve Light", code: "047", hex: "#E0B0FF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mauve", code: "048", hex: "#AF8FE9" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Antique Pink Middle", code: "049", hex: "#E2909B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Antique Pink", code: "050", hex: "#C08081" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Piglet Pink Light", code: "051", hex: "#FFD1DC" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Piglet Pink", code: "052", hex: "#F4C2C2" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Candy", code: "053", hex: "#FFB7D5" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lipstick", code: "054", hex: "#C21E56" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Purple", code: "055", hex: "#800080" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Esher Dirty Red", code: "056", hex: "#8B0000" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Tilt Bubble Pink", code: "057", hex: "#FF69B4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Fuchsia Pink", code: "058", hex: "#FF00FF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mad C Psycho Pink", code: "059", hex: "#DA70D6" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Telemagenta", code: "060", hex: "#CF3476" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Amaranth Red", code: "061", hex: "#E52B50" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "MACrew Purple", code: "062", hex: "#6A0DAD" },

  // Row 4: Purples & Violets (063-093)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Purple Violet", code: "063", hex: "#4E2A52" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Crocus", code: "064", hex: "#91709C" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lavender", code: "065", hex: "#B5A2C4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lilac", code: "066", hex: "#DCD0E1" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grape", code: "067", hex: "#6A2E78" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Blackberry", code: "068", hex: "#43182F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Currant", code: "069", hex: "#4D0F35" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Crazy Plum", code: "070", hex: "#663399" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Violet Dark", code: "071", hex: "#32174D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Violet", code: "072", hex: "#2E1A47" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Thistle", code: "073", hex: "#D8BFD8" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Viola Pastel", code: "074", hex: "#E6E6FA" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Viola Light", code: "075", hex: "#CCCCFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Viola Middle", code: "076", hex: "#9999FF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Viola", code: "077", hex: "#7F7FFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Viola Dark", code: "078", hex: "#4C4CFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Night Seen Blue", code: "079", hex: "#191970" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grape Middle", code: "080", hex: "#8A2BE2" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grape Dark", code: "081", hex: "#4B0082" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Purple Velvet", code: "082", hex: "#663399" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Light Violet", code: "083", hex: "#DA70D6" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Plum Middle", code: "084", hex: "#DDA0DD" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Nasty Sons Plum", code: "085", hex: "#8E4585" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Pigeon Blue Middle", code: "086", hex: "#738595" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Pigeon Blue", code: "087", hex: "#4863A0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Blueberry Light", code: "088", hex: "#ADD8E6" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Azure Blue Light", code: "089", hex: "#F0FFFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Azure Blue", code: "090", hex: "#007FFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Shock Blue Pastel", code: "091", hex: "#89CFF0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Shock Blue Light", code: "092", hex: "#0078BF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Shock Blue Middle", code: "093", hex: "#005A92" },

  // Row 5: Blues & Turquoise (094-131)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Shock Blue", code: "094", hex: "#0055A4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Tulip Blue Light", code: "095", hex: "#ADD8E6" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Tulip Blue Middle", code: "096", hex: "#0078BF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Tulip Blue", code: "097", hex: "#005A92" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Soten Blue Light", code: "098", hex: "#5D99C6" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ceramic Pastel", code: "099", hex: "#B8D5E5" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Jeans Blue", code: "100", hex: "#5D76CB" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Wild Wane Blue", code: "101", hex: "#1560BD" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Navy Blue", code: "102", hex: "#003366" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ultramarine Blue", code: "103", hex: "#120A8F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sapphire Blue", code: "104", hex: "#0F52BA" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Indigo", code: "105", hex: "#4B0082" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "ECB Prussian Blue Dark", code: "106", hex: "#003153" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Stormblue Middle", code: "106-1", hex: "#4F666A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Stormblue", code: "106-2", hex: "#3B4A4F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Stormblue Dark", code: "106-3", hex: "#242E32" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Petrol", code: "107", hex: "#005F6A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Deep-Sea Blue", code: "108", hex: "#004758" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Deep-Sea Blue Dark", code: "109", hex: "#002137" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ice-Blue Dark", code: "110", hex: "#ADD8E6" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Dolphin Blue", code: "111", hex: "#739199" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Petrol Blue", code: "112", hex: "#006A72" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cream Blue", code: "113", hex: "#E1EBEE" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Olympia Blue", code: "114", hex: "#005A92" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Aqua", code: "115", hex: "#00FFFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Alga", code: "116", hex: "#008F11" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Baby Blue", code: "117", hex: "#89CFF0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Crystal Blue Dark", code: "118", hex: "#4682B4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Blue Gin", code: "119", hex: "#625D71" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Verdigris", code: "120", hex: "#40826D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Caribbean", code: "121", hex: "#00819C" },

  // Row 6: Menthol & Greens (122-152)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Riviera Pastel", code: "122", hex: "#AFEEEE" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Riviera Light", code: "123", hex: "#20B2AA" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Taste Riviera Middle", code: "124", hex: "#008B8B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Riviera Dark", code: "125", hex: "#004040" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lagoon Blue", code: "126", hex: "#008080" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Martha Marine", code: "127", hex: "#273D3F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Turquoise Dark", code: "128", hex: "#004D4D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Nori", code: "129", hex: "#1C352D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Turquoise", code: "130", hex: "#002D2D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Gale Green", code: "131", hex: "#2F4F4F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Reed", code: "132", hex: "#B4C4A9" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Aquamarine", code: "133", hex: "#7FFFD4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Swamp", code: "134", hex: "#2D5D44" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Forest Green", code: "135", hex: "#1A2421" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Blueberry Pastel", code: "136", hex: "#D9E3F0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Calypso Light", code: "137", hex: "#E0FFFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Calypso Middle", code: "138", hex: "#AFEEEE" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Calypso Dark", code: "139", hex: "#00CED1" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Turquoise Green", code: "140", hex: "#40E0D0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Amazonas", code: "141", hex: "#3B7A57" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Turquoise Green Mid.", code: "142", hex: "#48D1CC" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Turquoise Green Dark", code: "142-2", hex: "#008B8B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Future Green", code: "143", hex: "#32CD32" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Menthol Light", code: "144", hex: "#E1F1E1" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Menthol", code: "145", hex: "#3EB489" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Universe Green", code: "146", hex: "#315E4D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lettuce Green", code: "147", hex: "#8FBC8F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Kiwi Pastel", code: "148", hex: "#D0F0C0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Kiwi Light", code: "149", hex: "#98FB98" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Kiwi", code: "150", hex: "#8EE53F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Dandelion", code: "151", hex: "#FED85D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Brilliant Green", code: "152", hex: "#00FF00" },

  // Row 7: Deep Greens & Earth (153-181)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grasshopper", code: "153", hex: "#00914C" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cream Green", code: "154", hex: "#C8E6C9" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Hippie Green", code: "155", hex: "#4CAF50" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "BACON Wasabi", code: "156", hex: "#8BC34A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cliff Green", code: "157", hex: "#004225" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Clover Green", code: "158", hex: "#3B7A57" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Juice Green", code: "159", hex: "#8EC63F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mr. Green", code: "160", hex: "#228B22" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Leaf Green Middle", code: "160-1", hex: "#32CD32" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Leaf Green", code: "161", hex: "#006400" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mighty Green", code: "162", hex: "#50C878" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Avocado", code: "163", hex: "#568203" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Fern Green", code: "164", hex: "#4F7942" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Moss Green", code: "165", hex: "#8A9A5B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Chromium Oxide Green", code: "166", hex: "#666B4E" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Green", code: "167", hex: "#1A2421" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Butterfly Green", code: "168", hex: "#00FF7F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Green Tea", code: "169", hex: "#D0F0C0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "P.JAY Green", code: "170", hex: "#355E3B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Amazonas", code: "171", hex: "#3B7A57" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Camouflage", code: "172", hex: "#6D7254" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Evil Olive", code: "173", hex: "#556B2F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Poison Green", code: "174", hex: "#32CD32" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Apple", code: "175", hex: "#8DB600" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sorbet Green", code: "176", hex: "#C5E384" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Soft Pastel", code: "177", hex: "#E8F5E9" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Carambola", code: "178", hex: "#E4D00A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Hemp", code: "179", hex: "#C8AD7F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Green Bean", code: "180", hex: "#679267" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Pear", code: "181", hex: "#D1E231" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Nature Green Light", code: "181-1", hex: "#9ACD32" },

  // Row 8: Browns, Ochres & Earth (181-2 - 202)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Nature Green Middle", code: "181-2", hex: "#6B8E23" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mustard", code: "182", hex: "#FFDB58" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mustard Yellow", code: "182-1", hex: "#E1AD01" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Khaki Green", code: "182-2", hex: "#8A865D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Khaki", code: "183", hex: "#C3B091" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ivory Light", code: "184", hex: "#F5F5DC" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sand Light", code: "184-1", hex: "#C2B280" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sand Middle", code: "184-2", hex: "#967117" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sand", code: "184-3", hex: "#766651" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Quartz Sand", code: "184-4", hex: "#D9D6CF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Quartz Sand Middle", code: "184-5", hex: "#B6B3AC" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Quartz Sand Light", code: "184-6", hex: "#95928C" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Furwhite", code: "184-7", hex: "#FDFDFD" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Milk Coffee", code: "185", hex: "#B08D57" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cappuccino", code: "186", hex: "#633927" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Espresso", code: "187", hex: "#4B3621" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mocca", code: "188", hex: "#3D2B1F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sahara Beige Light", code: "189", hex: "#EADDC4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sahara Beige Middle", code: "190", hex: "#D6C6B4" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Sahara Beige", code: "191", hex: "#BCB1A1" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Papyrus", code: "192", hex: "#E2D0BE" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Nougat", code: "193", hex: "#AD6F69" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Beige Brown", code: "194", hex: "#A67B5B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Apricot Beige", code: "195", hex: "#D4B097" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Labrador", code: "196", hex: "#5D5E53" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Camel", code: "197", hex: "#C19A6B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ocher Brown", code: "198", hex: "#A0522D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Orange Brown Light", code: "199", hex: "#CD853F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Orange Brown Middle", code: "200", hex: "#B7410E" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Orange Brown", code: "201", hex: "#8B4513" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cocoa Light", code: "202", hex: "#A67C52" },

  // Row 9: Deep Browns & Stones (203-227)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cocoa Middle", code: "203", hex: "#7B3F00" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Cocoa", code: "204", hex: "#483C32" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Caramel Light", code: "204-1", hex: "#D2B48C" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Caramel", code: "205", hex: "#C68E17" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Walnut", code: "206", hex: "#5D3A1A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Hazelnut", code: "207", hex: "#8B4513" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Chocolate Brown", code: "208", hex: "#3F301D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "CMP Dark Brown", code: "209", hex: "#3D2B1F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Tar Black", code: "210", hex: "#0D0D0D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Stone Grey Dark", code: "211", hex: "#3E4142" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Stone Grey Middle", code: "212", hex: "#5F6467" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Stone Grey Light", code: "213", hex: "#888B8D" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "TOAST Signal Black", code: "214", hex: "#28282B" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Grey Neutral", code: "215", hex: "#313639" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Dark Grey Neutral", code: "216", hex: "#4B4E53" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "CAPARSO Middle Grey Neutral", code: "217", hex: "#7E8182" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Light Grey Neutral", code: "218", hex: "#BCC2C5" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Mouse Grey", code: "219", hex: "#646B63" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Silver Dollar", code: "220", hex: "#AFAFAF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Gold Dollar", code: "220-1", hex: "#D4AF37" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Deep Black", code: "221", hex: "#0A0A0A" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Grey Light", code: "221-1", hex: "#2F2F2F" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Grey Middle", code: "221-2", hex: "#1C1C1C" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Black Grey Dark", code: "222", hex: "#000000" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Anthracite Grey Dark", code: "222-1", hex: "#3B3C36" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Anthracite Grey", code: "223", hex: "#383E42" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Anthracite Grey Middle", code: "223-1", hex: "#292E31" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grey Blue Dark", code: "224", hex: "#3A4B51" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Granite", code: "225", hex: "#616E73" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grey Blue Middle", code: "226", hex: "#7B8C92" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Rock Grey", code: "227", hex: "#625D5D" },

  // Row 10: Greys & Neons (228-236)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Grey Blue Light", code: "228", hex: "#B8C2C2" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Pebble Grey", code: "229", hex: "#B2BEB5" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Marble", code: "230", hex: "#E3E4E0" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Signal White", code: "231", hex: "#FFFFFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Yellow", code: "232", hex: "#FFFF00" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Orange", code: "233", hex: "#FF9900" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "ANTISTATIK Neon Red", code: "236-1", hex: "#FF3131" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Pink", code: "234", hex: "#FF00FF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Violet", code: "234-1", hex: "#9D00FF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Blue", code: "235", hex: "#0000FF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Turquoise", code: "235-1", hex: "#00FFFF" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Neon Green", code: "236", hex: "#00FF00" },

  // Row 11: Transparents (237-253)
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Melon Yellow Transp.", code: "237", hex: "#F68E0099" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Dare Orange Transp.", code: "238", hex: "#E94E1B99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Traffic Red Transp.", code: "239", hex: "#C00D0D99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Telemagenta Transp.", code: "240", hex: "#CF347699" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Currant Transp.", code: "241", hex: "#4D0F3599" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Ultramarine Blue Transp.", code: "242", hex: "#120A8F99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Shock Blue Transp.", code: "243", hex: "#0055A499" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Lagoon Blue Transp.", code: "244", hex: "#00808099" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Juice Green Transp.", code: "245", hex: "#8EC63F99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Hazelnut Transp.", code: "246", hex: "#8B451399" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Beige Brown Transp.", code: "247", hex: "#A67B5B99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Milk Coffee Transp.", code: "248", hex: "#B08D5799" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "TOAST Signal Black Transp.", code: "249", hex: "#28282B99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Middle Grey Neutral Transp.", code: "250", hex: "#80808099" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Signal White Transp.", code: "251", hex: "#FFFFFF99" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Clear Coat Gloss", code: "252", hex: "#FFFFFF33" },
  { brand: SprayBrand.MOLOTOW, line: SprayLine.MOLOTOW_PREMIUM, name: "Clear Coat Matt", code: "253", hex: "#FFFFFF11" },

  // --- OTHERS (Kept for compatibility) ---
  { brand: SprayBrand.MONTANA_COLORS, line: SprayLine.MTN_94, name: "Yosemite Yellow", code: "RV-103", hex: "#FFCC00" },
  { brand: SprayBrand.MONTANA_COLORS, line: SprayLine.MTN_94, name: "Black", code: "R-9011", hex: "#0C0C0C" },
  { brand: SprayBrand.MONTANA_CANS, line: SprayLine.MONTANA_GOLD, name: "Shock Blue", code: "S5000", hex: "#1E3A8A" },
  { brand: SprayBrand.MONTANA_CANS, line: SprayLine.MONTANA_GOLD, name: "Carbon", code: "S9000", hex: "#171717" },
];

export const BRAND_LINES: Record<SprayBrand, SprayLine[]> = {
  [SprayBrand.MOLOTOW]: [SprayLine.MOLOTOW_PREMIUM],
  [SprayBrand.MONTANA_COLORS]: [SprayLine.MTN_94, SprayLine.MTN_HARDCORE],
  [SprayBrand.MONTANA_CANS]: [SprayLine.MONTANA_GOLD, SprayLine.MONTANA_BLACK]
};

export const CAN_COVERAGE = 2.5;
